LEARN = {
  "savings": {
    "en": {"title": "Savings Calculator",
      "formula": "Available Savings = Income − Expenses\nMonths = Goal Price ÷ Available Savings",
      "terms": "Income: money you earn. Expenses: money you spend. Goal: what you save for.",
      "example": "Income ₹50,000, expenses ₹30,000 → saves ₹20,000/month. Goal ₹1,00,000 → 5 months.",
      "tip": "Save first, spend later. Even 10% of income helps."},
    "te": {"title": "పొదుపు కాలిక్యులేటర్",
      "formula": "మిగులు = ఆదాయం − ఖర్చులు\nనెలలు = లక్ష్య ధర ÷ మిగులు",
      "terms": "ఆదాయం: మీరు సంపాదించే డబ్బు. ఖర్చులు: మీరు ఖర్చు చేసే డబ్బు. లక్ష్యం: మీరు దేని కోసం దాస్తున్నారో అది.",
      "example": "ఆదాయం ₹50,000, ఖర్చులు ₹30,000 → నెలకు ₹20,000 పొదుపు. లక్ష్యం ₹1,00,000 → 5 నెలలు.",
      "tip": "ముందు పొదుపు చేయండి, తర్వాత ఖర్చు చేయండి."}},
  "emi": {
    "en": {"title": "EMI Calculator",
      "formula": "Months to repay n = −ln(1 − P × r ÷ EMI) ÷ ln(1 + r)\nP = loan, r = monthly rate (annual ÷ 12 ÷ 100), EMI = what you pay each month",
      "terms": "EMI: fixed monthly payment. Principal: loan amount. Your EMI must be more than the first month's interest.",
      "example": "₹1,00,000 at 10% with EMI ₹8,792 → about 12 months.",
      "tip": "A higher EMI finishes the loan sooner and saves interest."},
    "te": {"title": "EMI కాలిక్యులేటర్",
      "formula": "చెల్లించాల్సిన నెలలు n = −ln(1 − P × r ÷ EMI) ÷ ln(1 + r)\nP = రుణం, r = నెలవారీ వడ్డీ రేటు, EMI = ప్రతి నెలా చెల్లించే మొత్తం",
      "terms": "EMI: ప్రతి నెలా చెల్లించే స్థిర మొత్తం. అసలు: రుణ మొత్తం. మీ EMI మొదటి నెల వడ్డీ కంటే ఎక్కువగా ఉండాలి.",
      "example": "₹1,00,000, 10% వడ్డీ, EMI ₹8,792 → సుమారు 12 నెలలు.",
      "tip": "ఎక్కువ EMI చెల్లిస్తే రుణం త్వరగా తీరుతుంది, వడ్డీ ఆదా అవుతుంది."}},
  "gst": {
    "en": {"title": "GST Calculator",
      "formula": "Exclusive: GST = Price × Rate ÷ 100; Total = Price + GST\nInclusive: Base = Price ÷ (1 + Rate ÷ 100)",
      "terms": "GST: Goods and Services Tax. Exclusive: tax added on top. Inclusive: tax already inside the price.",
      "example": "₹1,000 at 18% exclusive → GST ₹180, total ₹1,180.",
      "tip": "Common slabs are 5%, 12%, 18% and 28%."},
    "te": {"title": "GST కాలిక్యులేటర్",
      "formula": "ఎక్స్‌క్లూజివ్: GST = ధర × రేటు ÷ 100; మొత్తం = ధర + GST\nఇన్‌క్లూజివ్: అసలు ధర = ధర ÷ (1 + రేటు ÷ 100)",
      "terms": "GST: వస్తు సేవల పన్ను. ఎక్స్‌క్లూజివ్: పన్ను అదనంగా. ఇన్‌క్లూజివ్: పన్ను ధరలోనే ఉంది.",
      "example": "₹1,000, 18% ఎక్స్‌క్లూజివ్ → GST ₹180, మొత్తం ₹1,180.",
      "tip": "సాధారణ రేట్లు 5%, 12%, 18%, 28%."}},
  "percentage": {
    "en": {"title": "Percentage Calculator",
      "formula": "Value = Total × Percentage ÷ 100",
      "terms": "Percent means 'out of 100'.",
      "example": "15% of 200 = 200 × 15 ÷ 100 = 30.",
      "tip": "10% of a number: move the decimal point one place left."},
    "te": {"title": "శాతం కాలిక్యులేటర్",
      "formula": "విలువ = మొత్తం × శాతం ÷ 100",
      "terms": "శాతం అంటే 'వందలో'.",
      "example": "200లో 15% = 200 × 15 ÷ 100 = 30.",
      "tip": "10% కోసం దశాంశ బిందువును ఒక స్థానం ఎడమకు జరపండి."}}
}
